services:
  postgres:
    container_name: postgres
    image: postgres:15.10-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      voz:
        ipv4_address: 10.0.0.100
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  voz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
    driver_opts:
      com.docker.network.bridge.name: voz

volumes:
  postgres-data:
    driver: local
